---
- name: Install unattended upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
  when: homelab_enable_unattended_upgrades

- name: Enable unattended upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
  when: homelab_enable_unattended_upgrades

- name: Remove unused APT packages
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
